title: Page
options:
  preview: false
  
files: true
  fields:
    caption:
      label: Caption
      type: text

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  wysiwyg
    buttons:
      - anchor
      - h1
      - unorderedlist
      - orderedlist
