title: Site

pages: default

options:
  preview: false

fields:
  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  email:
    label: Site Email (used for forms)
    type:  email
    
  copyright:
    label: Copyright
    type:  textarea
